services:
  # PHP FPM Service
  php:
    image: docker.io/wodby/php:latest
    volumes:
      - "./public:/var/www/html:z"
    user: "${UID}:${GID}"
  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - "./public:/var/www/html:z"
      - "./docker/default.conf:/etc/nginx/conf.d/default.conf:Z"
    depends_on:
      - php
      - mariadb

  # MariaDB Service
  mariadb:
    image: docker.io/mariadb:latest
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 3356:3306

  phpmyadmin:
    image: docker.io/phpmyadmin:latest
    depends_on:
      - mariadb
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 1080:80
